### ISSUE TITLE
System.Diagnostics.Process xxxx64 properties reported as not supported

### ISSUE THREAD

**Issue by danielmarbach** [dotnet/platform-compat#69] opened 2017-11-21 11:15 UTC
- PrivateMemorySize64
- PeakWorkingSet64
- PeakPagedMemorySize64
- PeakVirtualMemorySize64
...

are reported as not supported but it seems they are.

https://github.com/dotnet/standard/blob/9a379bc0aabb4c0ac8f0ef2cd4b14a1217ba4a8e/docs/comparisons/netstandard1.6_vs_netcoreapp1.1/System.Diagnostics.md

**Comment by pjanotti** [comment] 2017-12-14 22:33
Thanks for reporting this issue. This has the same root cause as #72 I will close this one and track the fix there.

**Closed by pjanotti** 2017-12-14 22:33 UTC
