### ISSUE TITLE
0.1.3-alpha: NRE in ExceptionAnalyzer

### ISSUE THREAD

**Issue by nphmuller** [dotnet/platform-compat#97] opened 2018-02-16 12:33 UTC
After updating from 0.1.2 to 0.1.3 the analyzers throw the following exception: `Microsoft.DotNet.Analyzers.Compatibility.Exceptions.ExceptionAnalyzer`.

I would like to provide more details, but I'm not sure how to get the entire StackTrace, since Visual Studio only outputs the following:
`Warning AD0001 Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Exceptions.ExceptionAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.`

**Comment by Krakean** [comment] 2018-02-22 13:36
Same here.
I dont think there is need to provide call stack - just enough to try to compile any medium-sized project in C# with a at least 3 projects, and this error can be easily reproduced.

**Comment by pjanotti** [comment] 2018-03-05 18:01
Perhaps a duplicate of #99? I am trying to see if there is a way to get more information about each AD0001 so we can be certain if it has a different root cause or not. In general, I would expect these to be caused by some pattern in the source code that we failed to test against.

**Comment by Krakean** [comment] 2018-03-05 19:44
@pjanotti 
May be. But hopefully my issue is fixed.
By the way, when platform-compat will be updated in nuget? Or at least some night build will be fine.

**Comment by pjanotti** [comment] 2018-03-06 05:17
@Krakean we are working on getting one out... should be soon.

@nphmuller I got the info on how to get callstacks for such issues: 

* Add a `<ErrorLog>` property to the csproj and it will capture stacks for analyzers crashes on next build, e.g.: `<ErrorLog>analyzerErrors.json</ErrorLog>`
*  On VS the AD0001 warnings just capture the callstack if it is triggered by IntelliSense, i.e.: if you are editing the specific file causing the exception (likely hard to find in large projects).

**Comment by nphmuller** [comment] 2018-03-06 09:13
@pjanotti Never mind. Managed to get a smaller log that was easier to anonymise.
https://gist.github.com/nphmuller/55174b8bbe17587e48223a342b6cc669

**Comment by pjanotti** [comment] 2018-03-08 05:17
@nphmuller I looked at the logs and looks like the issue in #96, anyway, we released 0.2.12-alpha earlier today, please, let's know if you still have any issues with this release.

**Comment by nphmuller** [comment] 2018-03-08 12:28
@pjanotti No more exceptions! Nice!

**Closed** 2018-03-08 15:42 UTC
